# プロジェクトのメイン設定
# "my-cloudflare-bbs" の部分は、あなたのアカウント内でユニークなWorker名に変更してください。
name = "my-cloudflare-bbs" 
main = "functions/api/[[path]].ts"
compatibility_date = "2023-12-01"
pages_build_output_dir = "."


[[d1_databases]]

binding = "MY_D1_DATABASE2"

database_name = "thread" 

database_id = "${D1_DATABASE_ID2}"

# レートリミッターのバインディング設定
# この設定は機密情報ではないため、直接記述して問題ありません
[unsafe.bindings]
[[unsafe.bindings]]
# Workerコード内で `env.RATE_LIMITER` としてアクセスするための名前
name = "RATE_LIMITER"
type = "rate_limiter"
# このプロジェクト内でユニークなID（任意の文字列でOK）
namespace_id = "1"
# 1秒間に1リクエストまで、同じIPアドレスからのリクエストを許可する設定
# （注意：Cache APIモデルではレート制限はPOSTリクエストにしかかかりません）
simple = { limit = 1, period = 1 }

# ローカル開発用の設定 (任意)
# `wrangler dev` を実行した際に、ここで指定したポートでサーバーが起動します
[dev]
port = 8788
local_protocol = "http"